language: java
jdk:
- openjdk8

install:
- mvn -N io.takari:maven:wrapper # git strips the wrapper jar file so we have to force its download during the build
- ./mvnw install -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "mbouchenoire-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
